import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

const root = new URL('..', import.meta.url)
const read = (path) => fs.readFileSync(new URL(path, root), 'utf8')

test('responsive UI keeps mobile hit targets, safe areas, and focus states', () => {
  const css = read('src/style.css')
  const app = read('src/App.vue')
  const account = read('src/AccountPanel.vue')
  const editor = read('src/MarkdownEditor.vue')

  assert.match(css, /height: 100dvh/)
  assert.match(css, /safe-area-inset-top/)
  assert.match(css, /\.format-tools \.toolbar-button \{ width: 48px; height: 48px; min-height: 48px/)
  assert.match(css, /\.drawer-scrim \{ position: fixed/)
  assert.match(css, /\.editor-pane:focus-within \{ box-shadow: inset 0 0 0 2px var\(--accent\)/)
  assert.match(editor, /outline: '2px solid var\(--accent\)'/)
  assert.match(editor, /pasteURLAsLink: true/)
  assert.match(editor, /lineWrappingCompartment\.of\(props\.lineWrapping \? EditorView\.lineWrapping : \[\]\)/)
  assert.match(editor, /defineExpose\(\{[^}]*goToLine/)
  assert.match(app, /:inert="modalOpen \|\| drawerOpen"/)
  assert.match(app, /@keydown\.tab="trapModalFocus\(\$event, settingsModal\)"/)
  assert.match(account, /@media \(pointer: coarse\)[\s\S]*\.account-panel button,[\s\S]*min-height: 48px/)
  assert.match(account, /\.account-create input,[\s\S]*font-size: 16px/)
})

test('visual tokens and scrollbars stay consistent across editor surfaces', () => {
  const css = read('src/style.css')
  const markdown = read('src/markdown.js')
  const document = read('index.html')
  const manifest = JSON.parse(read('public/manifest.webmanifest'))
  const icon = read('public/notide-icon.svg')
  const iconBackground = read('public/notide-icon-background.svg')

  assert.match(css, /--accent: #2F63BD/)
  assert.match(css, /--accent-hover: #24509C/)
  assert.match(css, /--accent-soft: #E8F2FF/)
  assert.match(css, /--accent-sky: #5A97F2/)
  assert.match(css, /--navy: #15344A/)
  assert.match(css, /--accent: #72A9F5/)
  assert.match(css, /--paper-deep: #121417/)
  assert.match(css, /--paper: #1A1C1F/)
  assert.match(css, /--surface-raised: #222529/)
  assert.match(css, /--danger: #b42318/)
  assert.match(css, /--scroll-track: #E7EDF4/)
  assert.match(css, /--scroll-thumb: #6B8299/)
  assert.match(css, /\.markdown-editor \.cm-scroller::-webkit-scrollbar/)
  assert.match(css, /\.markdown-body :is\(pre, table, \.katex-display, \.mermaid-block, \.tab-list\)/)
  assert.match(css, /scrollbar-color: var\(--scroll-thumb\) var\(--scroll-track\)/)
  assert.match(css, /@media \(pointer: coarse\)[\s\S]*width: 5px; height: 5px/)
  assert.match(css, /@media \(forced-colors: active\)[\s\S]*scrollbar-color: auto/)
  assert.doesNotMatch(css, /(^|[\s,{])\.(rail|sidebar|topbar|document-head|search-box)(?=[\s,{:.#])/m)
  assert.match(markdown, /primaryColor: '#E8F2FF'/)
  assert.match(markdown, /primaryBorderColor: '#72A9F5'/)
  assert.match(document, /name="theme-color" content="#15344A"/)
  assert.equal(manifest.theme_color, '#15344A')
  assert.equal(manifest.background_color, '#15344A')
  assert.match(icon, /fill="#15344A"/)
  assert.match(iconBackground, /fill="#15344A"/)
})

test('controls expose selected state and settings fields expose validation context', () => {
  const app = read('src/App.vue')

  assert.match(app, /:aria-pressed="Boolean\(activeNote\?\.favorite\)"/)
  assert.match(app, /:aria-pressed="Boolean\(activeNote\?\.pinned\)"/)
  assert.match(app, /:aria-pressed="viewMode === 'edit'"/)
  assert.match(app, /id="notide-sync-endpoint"[\s\S]*aria-describedby="sync-endpoint-help sync-connection-result"/)
  assert.match(app, /<AccountPanel[^>]*:endpoint="syncEndpoint"[^>]*:session="authSession"/)
  assert.match(app, /connectionState === 'error' \? 'alert' : 'status'/)
  assert.match(app, /aria-live="polite" aria-atomic="true"/)
})
